import type { CookiePath } from '@/types/cookiePath'

export function cookiePathsToScad(paths: CookiePath[]): string {
  const header = `// Cookie Cutter generated by Cookie Cutter Generator
// Open with OpenSCAD for high-quality STL export
$fn = 96;

`

  const modules = paths
    .map((p, index) => {
      const pts = p.points
        .map((pt) => `[${pt.x.toFixed(3)}, ${pt.y.toFixed(3)}]`)
        .join(', ')

      return `// ${p.label} (${p.mode})
module path_${index}() {
  difference() {
    linear_extrude(height = ${p.heightMm}) {
      polygon(points = [${pts}]);
    }
    ${
      p.wallThicknessMm > 0
        ? `
    translate([0, 0, -0.1])
    linear_extrude(height = ${p.heightMm + 0.2}) {
      offset(delta = -${p.wallThicknessMm})
        polygon(points = [${pts}]);
    }`
        : ''
    }
  }
}
`
    })
    .join('\n')

  const union = `
// Combine all paths
module cookie_cutter() {
  ${paths.map((_, i) => `translate([0, 0, ${paths[i].zOffsetMm}]) path_${i}();`).join('\n  ')}
}

cookie_cutter();
`

  return header + modules + union
}

export function downloadScadFile(
  paths: CookiePath[],
  filename = 'cookie-cutter.scad',
): void {
  const scadContent = cookiePathsToScad(paths)
  const blob = new Blob([scadContent], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)

  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.click()

  URL.revokeObjectURL(url)
}
